language: python
python:
  - '3.8'
install:
  - pip install -e .
script:
  - python -m unittest discover -s tests
deploy:
  provider: pypi
  user: "retxxxirt"
  password:
    secure: "RSKh1zJncaK1VjbBBXAADBeXCwnm6+pxdbdoyayf2yxWxDhcjB7R5pYj11J4qu7ZGSD0iE4pSLYS3JfPqq9RJ+nOQw12ZOI+/Ll7YfqO/HbiBOEzLg7TsRtLyfq9F0uQ+5EF7uR8druPDbdy1/MXqEca7q2lK1Tkpd92LcRQWrU/ASWuKNL41FuBtDqP/gsJnmlmb+TfOk6fPy/Tq9PXyQXbwBuPAsuY6dzv7UPGwgerNe+wTaOayhIvLRpk4mIZ+3R3V+6KAV3nDI3Y6YcoHyMxX+P8eTt/sj9VPNPxvLj+uu+QXd8LcUqVPzLaTpkPvw4qPp/g/KQps9IQIqDq7/FIjnesQHNHKR50gYNKuv+/iRvmaFC/DzC2nhpqEHZHFywBarIVvMGrYw9U2jPLxRearTr+qs92k3GK6Pn/P6yOcr3iRfUdS+N5mhBejoYkbRROcuD9SQrYfQpL+HEp0G6AYHfLJIXKAoYIw7d2avZNd3QnRsDfoeqhwW1hajD4EnsXgHoYRoaEp8pg/6qd6huEJPcgWkfzQJaddhEyndgFmQGpyyG6c1em20xgcv973PqBOdV129bBXQs4KshSklNMoyLMShyv7m4qQLJ26uik+78vqppAH/ASqOIpGe0vjLzBh+M2hkvrI7pJLkNIL9+jGnFORakpOMjRt5N+JCs="
  on:
    branch: production